// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdbConnect(arg1) {
  return window['go']['main']['App']['AdbConnect'](arg1);
}

export function AdbDisconnect(arg1) {
  return window['go']['main']['App']['AdbDisconnect'](arg1);
}

export function AdbPair(arg1, arg2) {
  return window['go']['main']['App']['AdbPair'](arg1, arg2);
}

export function CancelOpenFile(arg1) {
  return window['go']['main']['App']['CancelOpenFile'](arg1);
}

export function ClearAppData(arg1, arg2) {
  return window['go']['main']['App']['ClearAppData'](arg1, arg2);
}

export function CopyFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['CopyFile'](arg1, arg2, arg3);
}

export function DeleteFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteFile'](arg1, arg2);
}

export function DisableApp(arg1, arg2) {
  return window['go']['main']['App']['DisableApp'](arg1, arg2);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function EnableApp(arg1, arg2) {
  return window['go']['main']['App']['EnableApp'](arg1, arg2);
}

export function ExportAPK(arg1, arg2) {
  return window['go']['main']['App']['ExportAPK'](arg1, arg2);
}

export function ForceStopApp(arg1, arg2) {
  return window['go']['main']['App']['ForceStopApp'](arg1, arg2);
}

export function GetAppInfo(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAppInfo'](arg1, arg2, arg3);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetBackendLogs() {
  return window['go']['main']['App']['GetBackendLogs']();
}

export function GetDeviceIP(arg1) {
  return window['go']['main']['App']['GetDeviceIP'](arg1);
}

export function GetDeviceInfo(arg1) {
  return window['go']['main']['App']['GetDeviceInfo'](arg1);
}

export function GetDevices(arg1) {
  return window['go']['main']['App']['GetDevices'](arg1);
}

export function GetHistoryDevices() {
  return window['go']['main']['App']['GetHistoryDevices']();
}

export function GetLocalIP() {
  return window['go']['main']['App']['GetLocalIP']();
}

export function GetThumbnail(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetThumbnail'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallAPK(arg1, arg2) {
  return window['go']['main']['App']['InstallAPK'](arg1, arg2);
}

export function IsAppRunning(arg1, arg2) {
  return window['go']['main']['App']['IsAppRunning'](arg1, arg2);
}

export function IsRecording(arg1) {
  return window['go']['main']['App']['IsRecording'](arg1);
}

export function ListCameras(arg1) {
  return window['go']['main']['App']['ListCameras'](arg1);
}

export function ListDisplays(arg1) {
  return window['go']['main']['App']['ListDisplays'](arg1);
}

export function ListFiles(arg1, arg2) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2);
}

export function ListPackages(arg1, arg2) {
  return window['go']['main']['App']['ListPackages'](arg1, arg2);
}

export function Log(arg1, arg2) {
  return window['go']['main']['App']['Log'](arg1, arg2);
}

export function Mkdir(arg1, arg2) {
  return window['go']['main']['App']['Mkdir'](arg1, arg2);
}

export function MoveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveFile'](arg1, arg2, arg3);
}

export function OpenFileOnHost(arg1, arg2) {
  return window['go']['main']['App']['OpenFileOnHost'](arg1, arg2);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function OpenSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenSettings'](arg1, arg2, arg3);
}

export function RemoveHistoryDevice(arg1) {
  return window['go']['main']['App']['RemoveHistoryDevice'](arg1);
}

export function RestartAdbServer() {
  return window['go']['main']['App']['RestartAdbServer']();
}

export function RunAdbCommand(arg1, arg2) {
  return window['go']['main']['App']['RunAdbCommand'](arg1, arg2);
}

export function SelectRecordPath(arg1) {
  return window['go']['main']['App']['SelectRecordPath'](arg1);
}

export function SelectScreenshotPath(arg1) {
  return window['go']['main']['App']['SelectScreenshotPath'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['main']['App']['Shutdown'](arg1);
}

export function StartActivity(arg1, arg2) {
  return window['go']['main']['App']['StartActivity'](arg1, arg2);
}

export function StartApp(arg1, arg2) {
  return window['go']['main']['App']['StartApp'](arg1, arg2);
}

export function StartLogcat(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['StartLogcat'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StartRecording(arg1, arg2) {
  return window['go']['main']['App']['StartRecording'](arg1, arg2);
}

export function StartScrcpy(arg1, arg2) {
  return window['go']['main']['App']['StartScrcpy'](arg1, arg2);
}

export function StartWirelessServer() {
  return window['go']['main']['App']['StartWirelessServer']();
}

export function StopLogcat() {
  return window['go']['main']['App']['StopLogcat']();
}

export function StopRecording(arg1) {
  return window['go']['main']['App']['StopRecording'](arg1);
}

export function StopScrcpy(arg1) {
  return window['go']['main']['App']['StopScrcpy'](arg1);
}

export function SwitchToWireless(arg1) {
  return window['go']['main']['App']['SwitchToWireless'](arg1);
}

export function TakeScreenshot(arg1, arg2) {
  return window['go']['main']['App']['TakeScreenshot'](arg1, arg2);
}

export function TogglePinDevice(arg1) {
  return window['go']['main']['App']['TogglePinDevice'](arg1);
}

export function UninstallApp(arg1, arg2) {
  return window['go']['main']['App']['UninstallApp'](arg1, arg2);
}
