// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelOpenFile(arg1:string):Promise<void>;

export function ClearAppData(arg1:string,arg2:string):Promise<string>;

export function CopyFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteFile(arg1:string,arg2:string):Promise<void>;

export function DisableApp(arg1:string,arg2:string):Promise<string>;

export function DownloadFile(arg1:string,arg2:string):Promise<string>;

export function EnableApp(arg1:string,arg2:string):Promise<string>;

export function ExportAPK(arg1:string,arg2:string):Promise<string>;

export function ForceStopApp(arg1:string,arg2:string):Promise<string>;

export function GetAppInfo(arg1:string,arg2:string,arg3:boolean):Promise<main.AppPackage>;

export function GetDevices():Promise<Array<main.Device>>;

export function GetThumbnail(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InstallAPK(arg1:string,arg2:string):Promise<string>;

export function ListFiles(arg1:string,arg2:string):Promise<Array<main.FileInfo>>;

export function ListPackages(arg1:string,arg2:string):Promise<Array<main.AppPackage>>;

export function Mkdir(arg1:string,arg2:string):Promise<void>;

export function MoveFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenFileOnHost(arg1:string,arg2:string):Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function RunAdbCommand(arg1:Array<string>):Promise<string>;

export function SelectRecordPath():Promise<string>;

export function StartActivity(arg1:string,arg2:string):Promise<string>;

export function StartApp(arg1:string,arg2:string):Promise<string>;

export function StartLogcat(arg1:string,arg2:string):Promise<void>;

export function StartRecording(arg1:string,arg2:main.ScrcpyConfig):Promise<void>;

export function StartScrcpy(arg1:string,arg2:main.ScrcpyConfig):Promise<void>;

export function StopLogcat():Promise<void>;

export function StopRecording(arg1:string):Promise<void>;

export function StopScrcpy(arg1:string):Promise<void>;

export function UninstallApp(arg1:string,arg2:string):Promise<string>;
