// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAppData(arg1, arg2) {
  return window['go']['main']['App']['ClearAppData'](arg1, arg2);
}

export function CopyFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['CopyFile'](arg1, arg2, arg3);
}

export function DeleteFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteFile'](arg1, arg2);
}

export function DisableApp(arg1, arg2) {
  return window['go']['main']['App']['DisableApp'](arg1, arg2);
}

export function EnableApp(arg1, arg2) {
  return window['go']['main']['App']['EnableApp'](arg1, arg2);
}

export function ExportAPK(arg1, arg2) {
  return window['go']['main']['App']['ExportAPK'](arg1, arg2);
}

export function ForceStopApp(arg1, arg2) {
  return window['go']['main']['App']['ForceStopApp'](arg1, arg2);
}

export function GetAppInfo(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAppInfo'](arg1, arg2, arg3);
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallAPK(arg1, arg2) {
  return window['go']['main']['App']['InstallAPK'](arg1, arg2);
}

export function ListFiles(arg1, arg2) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2);
}

export function ListPackages(arg1, arg2) {
  return window['go']['main']['App']['ListPackages'](arg1, arg2);
}

export function Mkdir(arg1, arg2) {
  return window['go']['main']['App']['Mkdir'](arg1, arg2);
}

export function MoveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveFile'](arg1, arg2, arg3);
}

export function RunAdbCommand(arg1) {
  return window['go']['main']['App']['RunAdbCommand'](arg1);
}

export function StartApp(arg1, arg2) {
  return window['go']['main']['App']['StartApp'](arg1, arg2);
}

export function StartLogcat(arg1, arg2) {
  return window['go']['main']['App']['StartLogcat'](arg1, arg2);
}

export function StartScrcpy(arg1, arg2) {
  return window['go']['main']['App']['StartScrcpy'](arg1, arg2);
}

export function StopLogcat() {
  return window['go']['main']['App']['StopLogcat']();
}

export function UninstallApp(arg1, arg2) {
  return window['go']['main']['App']['UninstallApp'](arg1, arg2);
}
