// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function AdbConnect(arg1:string):Promise<string>;

export function AdbDisconnect(arg1:string):Promise<string>;

export function AdbPair(arg1:string,arg2:string):Promise<string>;

export function CancelOpenFile(arg1:string):Promise<void>;

export function ClearAppData(arg1:string,arg2:string):Promise<string>;

export function CopyFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteFile(arg1:string,arg2:string):Promise<void>;

export function DisableApp(arg1:string,arg2:string):Promise<string>;

export function DownloadFile(arg1:string,arg2:string):Promise<string>;

export function EnableApp(arg1:string,arg2:string):Promise<string>;

export function ExportAPK(arg1:string,arg2:string):Promise<string>;

export function ForceStopApp(arg1:string,arg2:string):Promise<string>;

export function GetAppInfo(arg1:string,arg2:string,arg3:boolean):Promise<main.AppPackage>;

export function GetAppVersion():Promise<string>;

export function GetBackendLogs():Promise<Array<string>>;

export function GetDeviceIP(arg1:string):Promise<string>;

export function GetDeviceInfo(arg1:string):Promise<main.DeviceInfo>;

export function GetDevices(arg1:boolean):Promise<Array<main.Device>>;

export function GetHistoryDevices():Promise<Array<main.HistoryDevice>>;

export function GetLocalIP():Promise<string>;

export function GetMITMBypassPatterns():Promise<Array<string>>;

export function GetProxySettings():Promise<{[key: string]: any}>;

export function GetProxyStatus():Promise<boolean>;

export function GetThumbnail(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InstallAPK(arg1:string,arg2:string):Promise<string>;

export function InstallProxyCert(arg1:string):Promise<string>;

export function IsAppRunning(arg1:string,arg2:string):Promise<boolean>;

export function IsRecording(arg1:string):Promise<boolean>;

export function ListCameras(arg1:string):Promise<Array<string>>;

export function ListDisplays(arg1:string):Promise<Array<string>>;

export function ListFiles(arg1:string,arg2:string):Promise<Array<main.FileInfo>>;

export function ListPackages(arg1:string,arg2:string):Promise<Array<main.AppPackage>>;

export function Log(arg1:string,arg2:Array<any>):Promise<void>;

export function Mkdir(arg1:string,arg2:string):Promise<void>;

export function MoveFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenFileOnHost(arg1:string,arg2:string):Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenSettings(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RemoveHistoryDevice(arg1:string):Promise<void>;

export function RestartAdbServer():Promise<string>;

export function RunAdbCommand(arg1:string,arg2:string):Promise<string>;

export function SelectRecordPath(arg1:string):Promise<string>;

export function SelectScreenshotPath(arg1:string):Promise<string>;

export function SetDeviceNetworkLimit(arg1:string,arg2:number):Promise<string>;

export function SetMITMBypassPatterns(arg1:Array<string>):Promise<void>;

export function SetProxyLatency(arg1:number):Promise<void>;

export function SetProxyLimit(arg1:number,arg2:number):Promise<void>;

export function SetProxyMITM(arg1:boolean):Promise<void>;

export function SetProxyWSEnabled(arg1:boolean):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartActivity(arg1:string,arg2:string):Promise<string>;

export function StartApp(arg1:string,arg2:string):Promise<string>;

export function StartDeviceMonitor():Promise<void>;

export function StartLogcat(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:string,arg6:boolean):Promise<void>;

export function StartNetworkMonitor(arg1:string):Promise<void>;

export function StartProxy(arg1:number):Promise<string>;

export function StartRecording(arg1:string,arg2:main.ScrcpyConfig):Promise<void>;

export function StartScrcpy(arg1:string,arg2:main.ScrcpyConfig):Promise<void>;

export function StartWirelessServer():Promise<string>;

export function StopAllNetworkMonitors():Promise<void>;

export function StopDeviceMonitor():Promise<void>;

export function StopLogcat():Promise<void>;

export function StopNetworkMonitor(arg1:string):Promise<void>;

export function StopProxy():Promise<string>;

export function StopRecording(arg1:string):Promise<void>;

export function StopScrcpy(arg1:string):Promise<void>;

export function SwitchToWireless(arg1:string):Promise<string>;

export function TakeScreenshot(arg1:string,arg2:string):Promise<string>;

export function TogglePinDevice(arg1:string):Promise<void>;

export function UninstallApp(arg1:string,arg2:string):Promise<string>;

export function UploadFile(arg1:string,arg2:string,arg3:string):Promise<void>;
