// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdbConnect(arg1) {
  return window['go']['main']['App']['AdbConnect'](arg1);
}

export function AdbDisconnect(arg1) {
  return window['go']['main']['App']['AdbDisconnect'](arg1);
}

export function AdbPair(arg1, arg2) {
  return window['go']['main']['App']['AdbPair'](arg1, arg2);
}

export function AnalyzeElementSelectors(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AnalyzeElementSelectors'](arg1, arg2, arg3, arg4);
}

export function AssertElementExists(arg1, arg2) {
  return window['go']['main']['App']['AssertElementExists'](arg1, arg2);
}

export function AssertElementText(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AssertElementText'](arg1, arg2, arg3, arg4);
}

export function CancelOpenFile(arg1) {
  return window['go']['main']['App']['CancelOpenFile'](arg1);
}

export function CleanupOldSessions(arg1) {
  return window['go']['main']['App']['CleanupOldSessions'](arg1);
}

export function ClearAppData(arg1, arg2) {
  return window['go']['main']['App']['ClearAppData'](arg1, arg2);
}

export function ClearSession(arg1) {
  return window['go']['main']['App']['ClearSession'](arg1);
}

export function ClickElement(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ClickElement'](arg1, arg2, arg3, arg4);
}

export function CopyFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['CopyFile'](arg1, arg2, arg3);
}

export function CreateSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2, arg3);
}

export function DeleteFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteFile'](arg1, arg2);
}

export function DeleteScriptTask(arg1) {
  return window['go']['main']['App']['DeleteScriptTask'](arg1);
}

export function DeleteTouchScript(arg1) {
  return window['go']['main']['App']['DeleteTouchScript'](arg1);
}

export function DeleteWorkflow(arg1) {
  return window['go']['main']['App']['DeleteWorkflow'](arg1);
}

export function DisableApp(arg1, arg2) {
  return window['go']['main']['App']['DisableApp'](arg1, arg2);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function EmitSessionEvent(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['EmitSessionEvent'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function EmitSessionEventFull(arg1) {
  return window['go']['main']['App']['EmitSessionEventFull'](arg1);
}

export function EmitSessionEventWithStep(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['EmitSessionEventWithStep'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function EnableApp(arg1, arg2) {
  return window['go']['main']['App']['EnableApp'](arg1, arg2);
}

export function EndSession(arg1, arg2) {
  return window['go']['main']['App']['EndSession'](arg1, arg2);
}

export function EnsureActiveSession(arg1) {
  return window['go']['main']['App']['EnsureActiveSession'](arg1);
}

export function ExecuteBatchOperation(arg1) {
  return window['go']['main']['App']['ExecuteBatchOperation'](arg1);
}

export function ExecuteSingleTouchEvent(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteSingleTouchEvent'](arg1, arg2, arg3);
}

export function ExecuteSingleWorkflowStep(arg1, arg2) {
  return window['go']['main']['App']['ExecuteSingleWorkflowStep'](arg1, arg2);
}

export function ExportAPK(arg1, arg2) {
  return window['go']['main']['App']['ExportAPK'](arg1, arg2);
}

export function FindAllElementsBySelector(arg1, arg2) {
  return window['go']['main']['App']['FindAllElementsBySelector'](arg1, arg2);
}

export function FindElement(arg1, arg2, arg3) {
  return window['go']['main']['App']['FindElement'](arg1, arg2, arg3);
}

export function FindElementAtPoint(arg1, arg2, arg3) {
  return window['go']['main']['App']['FindElementAtPoint'](arg1, arg2, arg3);
}

export function FindElementBySelector(arg1, arg2) {
  return window['go']['main']['App']['FindElementBySelector'](arg1, arg2);
}

export function ForceStopApp(arg1, arg2) {
  return window['go']['main']['App']['ForceStopApp'](arg1, arg2);
}

export function GenerateSelectorSuggestions(arg1, arg2) {
  return window['go']['main']['App']['GenerateSelectorSuggestions'](arg1, arg2);
}

export function GetActiveSession(arg1) {
  return window['go']['main']['App']['GetActiveSession'](arg1);
}

export function GetAppInfo(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAppInfo'](arg1, arg2, arg3);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetBackendLogs() {
  return window['go']['main']['App']['GetBackendLogs']();
}

export function GetBestSelector(arg1, arg2) {
  return window['go']['main']['App']['GetBestSelector'](arg1, arg2);
}

export function GetDeviceIP(arg1) {
  return window['go']['main']['App']['GetDeviceIP'](arg1);
}

export function GetDeviceInfo(arg1) {
  return window['go']['main']['App']['GetDeviceInfo'](arg1);
}

export function GetDeviceResolution(arg1) {
  return window['go']['main']['App']['GetDeviceResolution'](arg1);
}

export function GetDevices(arg1) {
  return window['go']['main']['App']['GetDevices'](arg1);
}

export function GetElementProperties(arg1, arg2) {
  return window['go']['main']['App']['GetElementProperties'](arg1, arg2);
}

export function GetElementsWithText(arg1, arg2) {
  return window['go']['main']['App']['GetElementsWithText'](arg1, arg2);
}

export function GetHistoryDevices() {
  return window['go']['main']['App']['GetHistoryDevices']();
}

export function GetLocalIP() {
  return window['go']['main']['App']['GetLocalIP']();
}

export function GetMITMBypassPatterns() {
  return window['go']['main']['App']['GetMITMBypassPatterns']();
}

export function GetProxyDevice() {
  return window['go']['main']['App']['GetProxyDevice']();
}

export function GetProxySettings() {
  return window['go']['main']['App']['GetProxySettings']();
}

export function GetProxyStatus() {
  return window['go']['main']['App']['GetProxyStatus']();
}

export function GetRecentEvents(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetRecentEvents'](arg1, arg2, arg3);
}

export function GetRecordingEventCount(arg1) {
  return window['go']['main']['App']['GetRecordingEventCount'](arg1);
}

export function GetRecordingStatus(arg1) {
  return window['go']['main']['App']['GetRecordingStatus'](arg1);
}

export function GetSelectorMatchCount(arg1, arg2) {
  return window['go']['main']['App']['GetSelectorMatchCount'](arg1, arg2);
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetSessionMetadata(arg1, arg2) {
  return window['go']['main']['App']['GetSessionMetadata'](arg1, arg2);
}

export function GetSessionTimeline(arg1, arg2) {
  return window['go']['main']['App']['GetSessionTimeline'](arg1, arg2);
}

export function GetSessions(arg1, arg2) {
  return window['go']['main']['App']['GetSessions'](arg1, arg2);
}

export function GetThumbnail(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetThumbnail'](arg1, arg2, arg3);
}

export function GetTouchInputDevice(arg1) {
  return window['go']['main']['App']['GetTouchInputDevice'](arg1);
}

export function GetUIHierarchy(arg1) {
  return window['go']['main']['App']['GetUIHierarchy'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InputNodeText(arg1, arg2, arg3) {
  return window['go']['main']['App']['InputNodeText'](arg1, arg2, arg3);
}

export function InputTextToElement(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['InputTextToElement'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function InstallAPK(arg1, arg2) {
  return window['go']['main']['App']['InstallAPK'](arg1, arg2);
}

export function InstallProxyCert(arg1) {
  return window['go']['main']['App']['InstallProxyCert'](arg1);
}

export function IsAppRunning(arg1, arg2) {
  return window['go']['main']['App']['IsAppRunning'](arg1, arg2);
}

export function IsPlayingTouch(arg1) {
  return window['go']['main']['App']['IsPlayingTouch'](arg1);
}

export function IsRecording(arg1) {
  return window['go']['main']['App']['IsRecording'](arg1);
}

export function IsRecordingTouch(arg1) {
  return window['go']['main']['App']['IsRecordingTouch'](arg1);
}

export function ListCameras(arg1) {
  return window['go']['main']['App']['ListCameras'](arg1);
}

export function ListDisplays(arg1) {
  return window['go']['main']['App']['ListDisplays'](arg1);
}

export function ListFiles(arg1, arg2) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2);
}

export function ListPackages(arg1, arg2) {
  return window['go']['main']['App']['ListPackages'](arg1, arg2);
}

export function LoadScriptTasks() {
  return window['go']['main']['App']['LoadScriptTasks']();
}

export function LoadTouchScripts() {
  return window['go']['main']['App']['LoadTouchScripts']();
}

export function LoadWorkflows() {
  return window['go']['main']['App']['LoadWorkflows']();
}

export function Log(arg1, arg2) {
  return window['go']['main']['App']['Log'](arg1, arg2);
}

export function LongClickElement(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['LongClickElement'](arg1, arg2, arg3, arg4, arg5);
}

export function LongPressAtCoordinates(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LongPressAtCoordinates'](arg1, arg2, arg3, arg4);
}

export function Mkdir(arg1, arg2) {
  return window['go']['main']['App']['Mkdir'](arg1, arg2);
}

export function MoveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveFile'](arg1, arg2, arg3);
}

export function OpenFileOnHost(arg1, arg2) {
  return window['go']['main']['App']['OpenFileOnHost'](arg1, arg2);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function OpenSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenSettings'](arg1, arg2, arg3);
}

export function PauseTask(arg1) {
  return window['go']['main']['App']['PauseTask'](arg1);
}

export function PerformNodeAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['PerformNodeAction'](arg1, arg2, arg3);
}

export function PickPointOnScreen(arg1, arg2) {
  return window['go']['main']['App']['PickPointOnScreen'](arg1, arg2);
}

export function PlayTouchScript(arg1, arg2) {
  return window['go']['main']['App']['PlayTouchScript'](arg1, arg2);
}

export function RemoveHistoryDevice(arg1) {
  return window['go']['main']['App']['RemoveHistoryDevice'](arg1);
}

export function RenameTouchScript(arg1, arg2) {
  return window['go']['main']['App']['RenameTouchScript'](arg1, arg2);
}

export function RestartAdbServer() {
  return window['go']['main']['App']['RestartAdbServer']();
}

export function ResumeTask(arg1) {
  return window['go']['main']['App']['ResumeTask'](arg1);
}

export function RunAdbCommand(arg1, arg2) {
  return window['go']['main']['App']['RunAdbCommand'](arg1, arg2);
}

export function RunScriptTask(arg1, arg2) {
  return window['go']['main']['App']['RunScriptTask'](arg1, arg2);
}

export function RunWorkflow(arg1, arg2) {
  return window['go']['main']['App']['RunWorkflow'](arg1, arg2);
}

export function SaveScriptTask(arg1) {
  return window['go']['main']['App']['SaveScriptTask'](arg1);
}

export function SaveTouchScript(arg1) {
  return window['go']['main']['App']['SaveTouchScript'](arg1);
}

export function SaveWorkflow(arg1) {
  return window['go']['main']['App']['SaveWorkflow'](arg1);
}

export function ScrollToElement(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ScrollToElement'](arg1, arg2, arg3, arg4, arg5);
}

export function SearchElementsAdvanced(arg1, arg2) {
  return window['go']['main']['App']['SearchElementsAdvanced'](arg1, arg2);
}

export function SearchElementsXPath(arg1, arg2) {
  return window['go']['main']['App']['SearchElementsXPath'](arg1, arg2);
}

export function SearchUIElements(arg1, arg2) {
  return window['go']['main']['App']['SearchUIElements'](arg1, arg2);
}

export function SelectAPKForBatch() {
  return window['go']['main']['App']['SelectAPKForBatch']();
}

export function SelectFileForBatch() {
  return window['go']['main']['App']['SelectFileForBatch']();
}

export function SelectRecordPath(arg1) {
  return window['go']['main']['App']['SelectRecordPath'](arg1);
}

export function SelectScreenshotPath(arg1) {
  return window['go']['main']['App']['SelectScreenshotPath'](arg1);
}

export function SetDeviceNetworkLimit(arg1, arg2) {
  return window['go']['main']['App']['SetDeviceNetworkLimit'](arg1, arg2);
}

export function SetMITMBypassPatterns(arg1) {
  return window['go']['main']['App']['SetMITMBypassPatterns'](arg1);
}

export function SetProxyDevice(arg1) {
  return window['go']['main']['App']['SetProxyDevice'](arg1);
}

export function SetProxyLatency(arg1) {
  return window['go']['main']['App']['SetProxyLatency'](arg1);
}

export function SetProxyLimit(arg1, arg2) {
  return window['go']['main']['App']['SetProxyLimit'](arg1, arg2);
}

export function SetProxyMITM(arg1) {
  return window['go']['main']['App']['SetProxyMITM'](arg1);
}

export function SetProxyWSEnabled(arg1) {
  return window['go']['main']['App']['SetProxyWSEnabled'](arg1);
}

export function SetSessionMetadata(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSessionMetadata'](arg1, arg2, arg3);
}

export function Shutdown(arg1) {
  return window['go']['main']['App']['Shutdown'](arg1);
}

export function StartActivity(arg1, arg2) {
  return window['go']['main']['App']['StartActivity'](arg1, arg2);
}

export function StartApp(arg1, arg2) {
  return window['go']['main']['App']['StartApp'](arg1, arg2);
}

export function StartBatchSync() {
  return window['go']['main']['App']['StartBatchSync']();
}

export function StartDeviceMonitor() {
  return window['go']['main']['App']['StartDeviceMonitor']();
}

export function StartLogcat(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['StartLogcat'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StartNetworkMonitor(arg1) {
  return window['go']['main']['App']['StartNetworkMonitor'](arg1);
}

export function StartProxy(arg1) {
  return window['go']['main']['App']['StartProxy'](arg1);
}

export function StartRecording(arg1, arg2) {
  return window['go']['main']['App']['StartRecording'](arg1, arg2);
}

export function StartScrcpy(arg1, arg2) {
  return window['go']['main']['App']['StartScrcpy'](arg1, arg2);
}

export function StartTouchRecording(arg1, arg2) {
  return window['go']['main']['App']['StartTouchRecording'](arg1, arg2);
}

export function StartWirelessServer() {
  return window['go']['main']['App']['StartWirelessServer']();
}

export function StopAllNetworkMonitors() {
  return window['go']['main']['App']['StopAllNetworkMonitors']();
}

export function StopBatchSync() {
  return window['go']['main']['App']['StopBatchSync']();
}

export function StopDeviceMonitor() {
  return window['go']['main']['App']['StopDeviceMonitor']();
}

export function StopLogcat() {
  return window['go']['main']['App']['StopLogcat']();
}

export function StopNetworkMonitor(arg1) {
  return window['go']['main']['App']['StopNetworkMonitor'](arg1);
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function StopRecording(arg1) {
  return window['go']['main']['App']['StopRecording'](arg1);
}

export function StopScrcpy(arg1) {
  return window['go']['main']['App']['StopScrcpy'](arg1);
}

export function StopTask(arg1) {
  return window['go']['main']['App']['StopTask'](arg1);
}

export function StopTouchPlayback(arg1) {
  return window['go']['main']['App']['StopTouchPlayback'](arg1);
}

export function StopTouchRecording(arg1) {
  return window['go']['main']['App']['StopTouchRecording'](arg1);
}

export function StopWorkflow(arg1) {
  return window['go']['main']['App']['StopWorkflow'](arg1);
}

export function SubmitSelectorChoice(arg1, arg2, arg3) {
  return window['go']['main']['App']['SubmitSelectorChoice'](arg1, arg2, arg3);
}

export function SwipeCoordinates(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SwipeCoordinates'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SwipeOnElement(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SwipeOnElement'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SwitchToWireless(arg1) {
  return window['go']['main']['App']['SwitchToWireless'](arg1);
}

export function TakeScreenshot(arg1, arg2) {
  return window['go']['main']['App']['TakeScreenshot'](arg1, arg2);
}

export function TapAtCoordinates(arg1, arg2, arg3) {
  return window['go']['main']['App']['TapAtCoordinates'](arg1, arg2, arg3);
}

export function TogglePinDevice(arg1) {
  return window['go']['main']['App']['TogglePinDevice'](arg1);
}

export function UninstallApp(arg1, arg2) {
  return window['go']['main']['App']['UninstallApp'](arg1, arg2);
}

export function UploadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3);
}

export function WaitElementGone(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WaitElementGone'](arg1, arg2, arg3, arg4);
}

export function WaitForElement(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WaitForElement'](arg1, arg2, arg3, arg4);
}
